### ISSUE TITLE
Building Spark Custom Image and HDFS

### ISSUE THREAD

**Issue by ignacio-dc** [mesosphere/spark-build#217]
Hello, I need to make a spark custom image with xgboost. After trying and failing I went with the simplest route and build a docker image with this docker file [https://github.com/mesosphere/spark-build/blob/2.1.0-2.2.0-1/docker/Dockerfile](url) and with the spark distribution the one that I downloaded from here [https://downloads.mesosphere.com/spark/assets/spark-2.2.0-1-bin-2.6.tgz](url). When I run it in dcos I get this error:
```
Exception in thread "main" java.lang.IllegalArgumentException: java.net.UnknownHostException: hdfs
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:374)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:668)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:604)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:148)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2598)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2632)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2614)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at org.apache.spark.util.Utils$.getHadoopFileSystem(Utils.scala:1859)
	at org.apache.spark.scheduler.EventLoggingListener.<init>(EventLoggingListener.scala:68)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:529)
	at com.despegar.ds2.combprod.trainer.jobs.models.TrainCombProdXGBoostJob$.main(TrainCombProdXGBoostJob.scala:33)
	at com.despegar.ds2.combprod.trainer.jobs.models.TrainCombProdXGBoostJob.main(TrainCombProdXGBoostJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:784)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:188)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:213)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:127)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.UnknownHostException: hdfs
```
If I run it without the custom image everything works fine.

**Comment by skonto** [comment]
It seems you dont have the hdfs xml files fetched in your container:
https://github.com/mesosphere/spark-build/blob/0bb17055f0205420714a3a88caf6a83dff538723/conf/spark-env.sh#L12-L13
You need to build the image by overriding the corresponding files found in spark distro with the ones in the conf dir in this project. 

Alternatively, check the top makefile in the project:
You could use the following steps.
set SPARK_DIST_URI=... along with other env vars
```make docker-dist
make stub-universe-url ```
This will create a stub universe with your distro to use in DCOS.

**Comment by ignacio-dc** [comment]
thanks, I include the spark-env.sh and now works
